In [1]:
import keras
import tensorflow as tf

print("Keras:", keras.__version__)
print("TensorFlow:", tf.__version__)

Keras: 3.15.1
TensorFlow: 2.21.0


In [2]:
print(tf.config.list_physical_devices("GPU"))

[]


In [3]:
import tensorflow as tf
x = tf.constant([10,20,30,40]) ### 1 D dimension tensor
print(x)
print("shape:", x.shape)
print("data type", x.dtype)

tf.Tensor([10 20 30 40], shape=(4,), dtype=int32)
shape: (4,)
data type <dtype: 'int32'>


In [6]:
### tensor for 2D
y = tf.constant([
    [10, 20, 30],
    [40, 50, 60]
])
print("shape", y.shape)
print("dimension", len(y.shape))

shape (2, 3)
dimension 2


In [7]:
from tensorflow import keras
layers = keras.layers.Dense(3)  ### 3 denotes the neurons , dense layer (hidden layer)
print(layers)

<Dense name=dense, built=False>


In [10]:
x = tf.constant([[1.0, 2.0, 3.0]])
output = layers(x)
print("input shape:", x.shape)
print("output shape:", output.shape)
print("output", output)

input shape: (1, 3)
output shape: (1, 3)
output tf.Tensor([[ 2.3975217  -0.35759282 -0.9954107 ]], shape=(1, 3), dtype=float32)


In [1]:
### activation function
## activation fn introduce non linearity , allowing neural network to learn complicated pattern
# ReLu activation fn negative number --- 0 and positive --- same positive number
import tensorflow as tf
import numpy as np
x = tf.constant([-3.0,-2.0,0,2,3])
relu_output = tf.nn.relu(x)
print("input", x.numpy())
print("ReLu", relu_output.numpy())

input [-3. -2.  0.  2.  3.]
ReLu [0. 0. 0. 2. 3.]


In [3]:
### basic model
from tensorflow import keras
model = keras.Sequential([
     keras.Input(shape=(3,)),
    keras.layers.Dense(16, activation="relu"), ### first hidden layer with 16 neuron with the activation fn of relu which converts negative valuee to zero and positive value with no changes
    keras.layers.Dense(8, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid") ### final output layer with activation fn as sigmoid fn , the sigmoid converts the output 0-1 which is useful for binary classification
])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 16)             │            64 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 209 (836.00 B)

 Trainable params: 209 (836.00 B)

 Non-trainable params: 0 (0.00 B)

In [4]:
model.compile(
    optimizer="adam", ### it is used for updating the model weight
    loss="binary_crossentropy",
    metrics=["accuracy"]
)
print("model compiled")


model compiled


In [5]:
import numpy as np
### now i am taking some example's of physiological feature too see model's output
## the physiological features are [heart_rate, temperature, respiratory_rate]
X_train = np.array([
     [72, 36.5, 16],
    [80, 36.8, 18],
    [90, 37.2, 20],
    [110, 38.5, 25],
    [120, 39.0, 28],
    [105, 38.2, 24]
], dtype=np.float32)
### 0 denotes less risk and 1 denotes high risk
y_train = np.array([
    0,0,0,1,1,1
], dtype=np.float32)
print("X shape:", X_train.shape)
print("y shape:", y_train.shape)


X shape: (6, 3)
y shape: (6,)


In [6]:
### training
history = model.fit(
    X_train,
    y_train,
    epochs = 20,
    verbose = 1  ### verbose is the level of output displayed during training and validation or it is used to see how much output i want to see duringg training
)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 936ms/step - accuracy: 0.5000 - loss: 14.7050
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 14.1516
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 13.5988
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 13.0465
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 12.4947
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 11.9434
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 11.3926
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 10.8423
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 10.2925
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 9.7432
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 9.2656
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss

In [7]:
X_test = tf.constant([
    [1.5, 2.5, 3.5],
    [4.5, 5.5, 6.5],
    [7.5, 8.5, 9.5]
], dtype=tf.float32)

y_test = tf.constant([
    [0],
    [1],
    [1]
], dtype=tf.float32)

print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_test shape: (3, 3)
y_test shape: (3, 1)


In [8]:
### evaluating the model
loss,accuracy = model.evaluate(
    X_test,
    y_test,
    verbose = 1
)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.3333 - loss: 1.2165
Test Loss: 1.2165077924728394
Test Accuracy: 0.3333333432674408


In [9]:
### prediction
prediction = model.predict(X_test)
print("Prediction:", prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
Prediction: [[0.35174292]
 [0.23639861]
 [0.16968364]]


In [10]:
predicted_classes = (prediction >= 0.5).astype(int)

print("Predicted classes:")
print(predicted_classes)

Predicted classes:
[[0]
 [0]
 [0]]


In [11]:
print("Actual classes:")
print(y_test.numpy())

print("Predicted classes:")
print(predicted_classes)

Actual classes:
[[0.]
 [1.]
 [1.]]
Predicted classes:
[[0]
 [0]
 [0]]
